theme: jekyll-theme-minimal
title: Chanho Park
subtitle: Curriculum vitae
name: Chanho Park
logo: /assets/img/profile-image.jpg
description: This page is curriculum vitae of chanho park
description: ch.park@yonsei.ac.kr
